Hoft/FPG-71: Added background music
fastPaws-game/fast-paws pull request #90
Opened 2023-06-07 04:08 UTC by mrHoft

- Сгенерировал с помощью AI несколько музыкальных треков. Пока выложил только один с коротким мотивом, который мало весит и в цикле получается вполне динамичный саундтрек. Следуя концепции игры, для каждой локации должна быть своя музыкальная тема, но у нас локация пока одна, поэтому и не стал заливать лишние файлы.
- Реализовал пред загрузку `Audio` элемента через наш `ResourceLoader`
- Добавил довольно крутой хук `useAudio`, идею которого позаимствовал у Lunatics. Никакого плагиата, использована только концепция управления `Audio`. Заложил основу для подключения кроме музыки ещё и внутриигровых звуков. С самими звуками пока не заморачивался потому что подбор сэмплов это работа на несколько дней, для меня во всяком случае, потому что я не звукорежиссёр и у меня нет ни наработок ни доступа к соответствующим базам.
- Переключение звука производится заблаговременно добавленным в игровой интерфейс элементом.

Попытался повторить апи для сохранения настроек звука по типу `Theme` но пока не разобрался как туда пихать разом раздельные настройки уровня звука (как бы не очень то и нужно, но хочется). @Vakulina выручай!

2023-06-13 18:23 UTC, MSolomahin requested changes

2023-06-13 18:23 UTC, MSolomahin commented on packages/client/src/api/SettingsApi.ts
> +  public getSoung = () => fetchApiV1.get<number>('/sound')
Тут наверно getSound а не getSoung?

2023-06-13 18:23 UTC, MSolomahin commented on packages/client/src/components/Game.tsx
> +    if (!isAuth || !user) return
Лучше оставить как было

2023-06-13 18:23 UTC, MSolomahin commented on packages/client/src/engine/Engine.ts
> +    if (this.target.isBarrier) this.playAudio('sound.impact')
Лучше явно написать в три строчки

2023-06-13 18:23 UTC, MSolomahin commented on packages/client/src/hooks/useAudio.tsx
> +      // setActiveMusic(name)
Удаляй комментарии

2023-06-13 18:23 UTC, MSolomahin commented on packages/client/src/hooks/useAudio.tsx
> +      if (state) play(activeMusic)
Лучше явно а не в одну строку

2023-06-13 18:23 UTC, MSolomahin commented on packages/client/src/main.tsx
> +  // <React.StrictMode>
Если тестишь, то возвращай потом то что комментил

2023-06-13 18:23 UTC, MSolomahin commented on packages/client/src/store/settings/SettingsSlice.ts
> +    // addCase cannot be called with two reducers for the same action type
Это ошибка, ее надо решать, а не писать в пр в комментах)

2023-06-14 01:06 UTC, mrHoft commented on packages/client/src/store/settings/SettingsSlice.ts
> +    // addCase cannot be called with two reducers for the same action type
Я для тебя это написал и дал ссылку на это место с просьбой помочь разобраться.

2023-06-14 08:10 UTC, Vakulina commented on packages/client/src/store/settings/SettingsSlice.ts
> +    setTheme: (state, action: PayloadAction<SettingsSlice['theme']>) => {
Попробуй так
 extraReducers: (builder) => {
    builder.addCase(buildChangeTheme, (state, action) => {
      state.theme = action.payload;
    });
    builder.addCase(buildChangeMusic, (state, action) => {
      state.music = action.payload;
    });
    builder.addCase(buildChangeSound, (state, action) => {
      state.sound = action.payload;
    });
    builder.addCase(buildChangeLanguage, (state, action) => {
      state.language = action.payload;
    });
  },

2023-06-14 08:26 UTC, MSolomahin commented on packages/client/src/store/settings/SettingsActions.ts
> +export const changeTheme = createAsyncThunk('theme/changeTheme', async (theme: ThemeVariants, { rejectWithValue }) => {
Имена у экшенов должны быть разными, не только theme/changeTheme

2023-06-14 08:26 UTC, MSolomahin commented on packages/client/src/store/settings/SettingsSlice.ts
> +    // addCase cannot be called with two reducers for the same action type
Это не делается в пр, пиши об этом в чат.
Ошибка в packages/client/src/store/settings/SettingsActions.ts

2023-06-14 23:57 UTC, mrHoft commented
@bin-umar прошу прощения за лишнюю задачу в одном PR

Взялся написать api для сохранения настроек звука. Не то чтобы это был необходимый функционал: помнить для каждого пользователя включен у него звук или нет, но как хороший тон,- весьма желательно.

Вот в итоге сюда дополнительно и попали слайсеры, санки, редьюсеры, экшены и пр. модули для работы с хранилищем. Решил притормозить, иначе ещё и серверная часть добавилась.

По задаче можно просмотреть только `src/hooks/useAudio.tsx`, но если удастся ознакомиться и с остальным то буду дополнительно признателен!

Помимо useAudio там претерпел изменения ещё компонент отвечающий за интерфейс из-за security policy браузера, о чём я написал выше в описании PR.

2023-06-15 07:30 UTC, MSolomahin approved these changes

2023-06-15 07:48 UTC, mrHoft commented on packages/client/src/components/Game.tsx
>    const [tooltip, setTooltip] = useState('')
Возник вопрос по поводу оптимизации реакт-компонент:
Вот есть компонент GamePage с кучей стейтов, которые он прокидывает в дочерние компоненты.
Стейты меняются через колбеки в игре и происходит это довольно часто. При их смене происходит выполнение всего содержимого компонента.
Это видно, если добавить console.log, к примеру. Ну или на примере useAudio, вызов которого есть в первой строчке: все действия в нём повторяются при каждом событии в игре и по несколько раз потому что одно событие зачастую меняет сразу несколько стейтов.
Понятно что это не обновление DOM и там нет какой то тяжёлой логики но есть запросы к хранилищу, к примеру. Плюс виртуальный колбэк, который я опрометчиво добавил напрямую в параметры вызова вероятно будет на своё создание "отъедать" кусочки памяти.
Существует ли какая то возможность это оптимизировать?

2023-06-15 11:20 UTC, Vakulina commented on packages/client/src/components/Game.tsx
>    const [tooltip, setTooltip] = useState('')
Еще можно рассмотреть возможность полностью избавиться от пропсов в компоненте с игрой и его дочерних компонентах. Добавить контекст. В теории это может уменьшить количество перерендеров.
Но эффективно это будет, кажется, только в случае, если разобьем слой InterfaceLayer на несколько независимых.

2023-06-15 11:20 UTC, Vakulina commented on packages/client/src/components/Game.tsx
>    const [tooltip, setTooltip] = useState('')
Вообще, не вижу в этом необходимости. Игра не "лагает" и перерендеров не так много

2023-06-15 11:21 UTC, Vakulina approved these changes

2023-06-15 19:16 UTC, bin-umar commented on packages/client/src/hooks/useAudio.tsx
> +      if (state) play(activeMusic)
@MSolomahin согласен! https://learn.javascript.ru/coding-style#figurnye-skobki

2023-06-15 19:18 UTC, bin-umar commented on packages/client/src/store/settings/SettingsSlice.ts
> +    // addCase cannot be called with two reducers for the same action type
В ПР-е можно самому написать коммент в нужную строчку и скинуть ссылку, так удобнее чем через комменты.

2023-06-15 19:26 UTC, bin-umar commented on packages/client/src/api/SettingsApi.ts
> +  public putLanguage(value: string) {
Лучше называть updateLanguage

2023-06-16 03:19 UTC, bin-umar approved these changes
Не вижу критических моментов, за исключением оставленных мелких замечаний и рекомендаций, код в целом написан достаточно читабельно.

2023-06-16 07:28 UTC, mrHoft commented on packages/client/src/components/Game.tsx
> +    playAudio('music.mountains')
useAudio с этим разберётся: у него есть соответствующие проверки и сообщения.
А водить дополнительный файл с типизацией столь динамической части как используемые ресурсы это дополнительные действия, о которых нужно помнить при любом добавлении/изменении.
Детальная типизация кода это, несомненно важно. А тут... может ещё понимание мудрости такого подхода не снизошло и я вижу только недостатки.

2023-06-16 07:29 UTC, mrHoft commented on packages/client/src/store/settings/SettingsSlice.ts
> +  language: string // 'en' | 'ru' | 'de' | 'fr'
Это пока только заготовка на будущее. Указал комментом как нужно будет сделать.

2023-06-16 07:33 UTC, mrHoft commented on packages/client/src/hooks/useAudio.tsx
> +  const switchAudio = (state: boolean) => {
Вообще беда с этими audio, music, sound. Все они как бы одно и в то же время разные. Пока ничего более подходящего чем добавлять volume, enable, switch не придумал :(

2023-06-16 07:41 UTC, mrHoft commented on packages/client/src/hooks/useAudio.tsx
> +  const playAudio = (name: string) => {
mute и play это внутренние вспомогательные функции, которые недоступны извне.
Учитывая что play вызывается только из playAudio то можно было объединить в одну. Посчитал что так нагляднее. Но, пожалуй, можно и объединить для краткости.

2023-06-16 08:00 UTC, mrHoft commented on packages/client/src/hooks/useAudio.tsx
> +    })
@bin-umar если есть идеи и время то буду признателен за комментарий к этому безобразию.

Обработчик ошибки добавлен из-за security polycy браузера, который отказывается воспроизводить музыку при старте приложения, если пользователь ранее с ним никак не взаимодействовал.
- Смущает наличие такой политики в принципе.
- Сильно не нравится цепочка колбеков, растянувшаяся аж на три слоя компонент чтоб визуально донести до пользователя что звук сейчас выключен.
- Не уверен насколько это корректно, не разбираясь в сути ошибки одинаково обрабатывать любую из них как "отключенный звук".

2023-06-19 20:19 UTC, bin-umar commented on packages/client/src/hooks/useAudio.tsx
> +    })
Сори что с опозданием, надеюсь актуально.

- Смущает наличие такой политики в принципе.

А почему смущает? Мне кажется нормальная политика :)

- Сильно не нравится цепочка колбеков, растянувшаяся аж на три слоя компонент чтоб визуально донести до пользователя что звук сейчас выключен.

Для решения этой проблемы (callback hell) и добавили async/await, почему бы не попробовать их?

- Не уверен насколько это корректно, не разбираясь в сути ошибки одинаково обрабатывать любую из них как "отключенный звук".

Формально так и есть, ты попробовал воспроизвести, но не получилось, ошибка. Какая там ошибка, может быть важным если вы например логируете клиентские ошибки, в данном случае зачем вам знать что какая ошибка?

2023-06-21 02:24 UTC, mrHoft commented on packages/client/src/hooks/useAudio.tsx
> +    })
Спасибо за ответ! Актуально. Дождался. Тебе удалось развеять мои сомнения!

2023-06-21 02:24 UTC, merged